apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cassandra
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cql
      protocol: TCP
      name: cql
  selector:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/instance: {{ .Release.Name }}
